"""Download the web fonts once and inline them as data URIs.

The published artifact links to Google Fonts, which is fine because it is viewed
online. A copy handed to someone on a memory stick cannot rely on that, so this
bakes the font files into web/fonts.css and the standalone build embeds them.

Run it only when the font choices change; the result is checked in so that
build.py never needs a network.

    python fetch_fonts.py
"""

import base64
import io
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "web", "fonts.css")

# Only the weights the stylesheet actually asks for.
FAMILIES = [
    ("Chivo", "wght@700"),
    ("IBM+Plex+Sans", "wght@400;500;600"),
    ("IBM+Plex+Mono", "wght@400;500"),
]

# A modern UA is what makes Google serve woff2 rather than a legacy format.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

# The page is English plus a few symbols, so Cyrillic and Vietnamese would be
# dead weight. Greek earns its place: the ohm sign lives there.
WANTED_SUBSETS = {"latin", "latin-ext", "greek"}


def get(url, binary=False):
    request = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(request, timeout=30) as response:
        data = response.read()
    return data if binary else data.decode("utf-8")


def main():
    blocks = []
    total = 0
    cache = {}

    for family, axis in FAMILIES:
        url = "https://fonts.googleapis.com/css2?family=%s:%s&display=swap" % (family, axis)
        try:
            css = get(url)
        except Exception as error:
            print("could not fetch %s: %s" % (family, error))
            return 1

        # Google labels each face with a /* subset */ comment just above it.
        for subset, block in re.findall(
                r"/\*\s*([a-z-]+)\s*\*/\s*(@font-face\s*\{[^}]*\})", css):
            if subset not in WANTED_SUBSETS:
                continue
            match = re.search(r"src:\s*url\((https://[^)]+\.woff2)\)", block)
            if not match:
                continue
            font_url = match.group(1)
            if font_url not in cache:
                cache[font_url] = get(font_url, binary=True)
                total += len(cache[font_url])
            encoded = base64.b64encode(cache[font_url]).decode("ascii")
            blocks.append(block.replace(
                "url(%s)" % font_url,
                "url(data:font/woff2;base64,%s)" % encoded))

    if not blocks:
        print("no font faces found")
        return 1

    header = ("/* Generated by fetch_fonts.py. Google Fonts, embedded so the\n"
              "   standalone page renders identically with no network. */\n")
    with io.open(OUT, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(header + "\n".join(blocks) + "\n")

    size = os.path.getsize(OUT)
    print("%d font faces, %.0f KB of woff2, %.0f KB of CSS written to web/fonts.css"
          % (len(blocks), total / 1024.0, size / 1024.0))
    return 0


if __name__ == "__main__":
    sys.exit(main())
